### ISSUE TITLE
能设置在底部弹出的时候距离底部的距离吗，类似饿了么，美团购物车底部弹出的那种

### ISSUE THREAD

**Issue by Easyzhan** [qcc107/UIViewController-CBPopup#1]
如题

**Comment by qcc107** [comment]
不错的建议，扩展了一个接口，可以传入margin参数😆  @Easyzhan

**Comment by Easyzhan** [comment]
貌似设置了margin之后点击背景没反应了，感觉美团，饿了么那种应该是背景也跟着margin的样子😆

**Comment by qcc107** [comment]
如果要点击背景消失，请确保overlayDismissEnabled 参数设置的为YES
